# Wire up travis
language: python
sudo: false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=py2-cover,py3-cover,coverage

install:
  - travis_retry pip install tox
  - if [[ $TOXENV == 'py32' ]]; then travis_retry pip install "virtualenv<14" ; fi

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
